language: generic
sudo: require
services:
  - docker

before_install:
  - docker build -t mopitz199/react-app-test-prod .

script:
  - docker run -e CI=true mopitz199/react-app-test-prod

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
  bucket: "react-docker-test"
  skip_cleanup: true
  local_dir: build
  acl: public_read
  on:
    branch: master